# This workflow installs dependencies, pulls Docker images, and runs all tests

name: Glotter

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths: &watch_paths
      - "archive/**"
      - ".glotter.yml"
      - "repo-config.yml"
      - ".github/workflows/test-suite.yml"
      - "pyproject.toml"
      - "poetry.lock"
      - "scripts/run_tests.py"
      - "!**/*.md"

  pull_request:
    branches: [main]
  schedule:
    # Run every Wednesday at 10:39 UTC (randomly chosen)
    - cron: "39 10 * * 3"

jobs:
  # Detect changed files
  changed-files:
    name: Changed Files
    runs-on: ubuntu-latest

    outputs:
      should_run: ${{ steps.detect.outputs.exists }}
      files: ${{ steps.detect.outputs.files }}

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Detect changes
        id: detect
        uses: yumemi-inc/changed-files@v3
        with:
          patterns: |
            archive/**
            .glotter.yml
            repo-config.yml
            .github/workflows/test-suite.yml
            pyproject.toml
            poetry.lock
            scripts/run_tests.py
            !**/*.md

      - name: Show changed files
        if: steps.detect.outputs.exists == 'true'
        run: |
          echo "Changed files:"
          printf '%s\n' ${{ steps.detect.outputs.files }}

  # Run tests
  testing:
    name: "Test Suite"
    needs: changed-files

    if: >
      needs.changed-files.outputs.should_run == 'true' || github.event_name ==
      'schedule'

    runs-on: ubuntu-latest

    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v5
        with:
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-cached-tools: true

      - uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Load repo config
        id: config
        uses: pietrobolcato/action-read-yaml@1.1.0
        with:
          config: repo-config.yml

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ steps.config.outputs['python-version'] }}

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: ${{ steps.config.outputs['poetry-version'] }}

      - name: Install Dependencies
        run: poetry install

      - name: Check for Bad Files
        run: poetry run glotter check

      - name: Run test suite
        run: |
          poetry run python scripts/run_tests.py \
            --event "${{ github.event_name }}" \
            --num-batches "${{ steps.config.outputs['num-batches'] }}" \
            --parallel \
            --remove "${{ needs.changed-files.outputs.files }}"

  # Because testing uses a matrix, we need this job for branch protections
  test-results:
    name: Test Results
    needs: testing
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Validate outcome
        run: |
          case "${{ needs.testing.result }}" in
            success|skipped)
              exit 0
              ;;
            *)
              exit 1
              ;;
          esac
